#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk/betterdesk /usr/bin/betterdesk
	ln -f -s /usr/share/rustdesk/betterdesk /usr/bin/rustdesk
	rm -f /usr/share/applications/rustdesk.desktop

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/rustdesk.service ]; then
			rm /etc/systemd/system/rustdesk.service /usr/lib/systemd/system/rustdesk.service /usr/lib/systemd/user/rustdesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk/files/systemd/rustdesk.service /usr/lib/systemd/system/rustdesk.service
		systemctl daemon-reload
		systemctl enable rustdesk
		systemctl start rustdesk
	fi
	update-desktop-database >/dev/null 2>&1 || true
fi
